# Generated by Django 4.2.11 on 2024-05-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.IntegerField()),
                ('user_guess_number', models.IntegerField(blank=True, null=True)),
                ('counting_trial', models.IntegerField(default=0)),
            ],
        ),
    ]
